### ISSUE TITLE
Don't start

### ISSUE THREAD

**Issue by Dengor1984** [rench/homebridge-smarthome#3]
Why i have this issues?
![img_2732](https://user-images.githubusercontent.com/28712832/27985314-6309ec7c-63f1-11e7-8ff9-176dd0be8d02.PNG)
![img_2735](https://user-images.githubusercontent.com/28712832/27985325-87712ecc-63f1-11e7-83bb-d1517618085f.PNG)
![img_2736](https://user-images.githubusercontent.com/28712832/27985326-879acdf4-63f1-11e7-8ddd-edbca49eaf6c.PNG)

**Comment by Dengor1984** [comment]
Homebridge 4.22
Node 7.10

**Comment by Dengor1984** [comment]
My config:

{
	"bridge": {
		"name": "Homebridge",
		"username": "F0:B4:29:CF:B7:F7",
		"port": 36640,
		"pin": "000-00-001"
	},
"accessories": [ 
        {
  "accessory": "PiTemperature",
  "name": "Raspberry PI Temperature"
}],
 "platforms": [
    {"platform": "smarthome-mijia",
      "web": {"port": 8888},
      "mijia": {"sids": ["xxxx"],
        "passwords": ["xxxx"],
        "devices": [
          {
            "sid": "Yeelight 001",
            "name": "Yeelight",
            "type": "wifi",
            "model": "light"
          }
]
}
}
]
}

**Comment by Dengor1984** [comment]
Sids and password i have changed to xxxx

**Comment by rench** [comment]
i think if you don't have gateway ,just let the config like 
```
"sids":[],
"passwords":[]
```
And make a update action.
Then print out the error message and whole config.json.

**Comment by Dengor1984** [comment]
I have Gateway v2, and do sids and passwords as usual in other worked plugins

**Comment by Dengor1984** [comment]
First i have the error, when i have in subdevices curtain.
When i have delite the curtain - i have error with wall switch, when i delite wall switch, i have error with another device...

**Comment by rench** [comment]
delite -> delete?
where did you delete the curtain?

please print out error message if you would like to .

**Comment by Dengor1984** [comment]
I have delite the curtain from device list in MiHome app, and after i had error messages which i have shown before...

**Comment by Dengor1984** [comment]
And firstwall at start plugin i have broadlink error message. After i delite broadlink in index.js, i have errors with aqara devices!(

**Comment by rench** [comment]
oh,it's very said. if you are using the plug,just reinstall and clean cache accessory.
