### ISSUE TITLE
Compatibility list 

### ISSUE THREAD

**Issue by prbreezy** [rench/homebridge-smarthome#5]
Hi,
I'm about to buy the Xiaomi smart hub with differents sensor I've seen this new model : 
http://www.gearbest.com/access-control/pp_626703.html?wid=21 which is not in your list but I beleive your code detect certain type device from the hub and can retrieve the info so any device should be compatible?

Thank you!

**Comment by rench** [comment]
it is already  compatible. Just see `Aqara Magent`.

**Comment by prbreezy** [comment]
Thank you !
