### ISSUE TITLE
几个问题哈

### ISSUE THREAD

**Issue by zhfish** [rench/homebridge-smarthome#7]
1. 纯自用的？我闲的无聊搜到的。。
2. 设备能否对应下中文名称？方便识别
3. 希望加入米家空调控制器
相关
`https://github.com/takatost/homebridge-mi-ac-partner`
4. 文档去哪找的啊？
绿米官网的文档仅有几个设备。
5. 能否出个备份命名的小工具，或者配置？，每次清除缓存调试，名字都没了

**Comment by rench** [comment]
thank for your suggestion.

1. just for myself as a hobby.
2. i think it's a good suggestion.
3. the `ac partner` is being hack and test,i think i will integrate when it be stable.
4. if you can find the lumi opencloud website,i think you call find some word(.doc) staff too.
5. after step 2.
