### ISSUE TITLE
ReferenceError: miio is not defined

### ISSUE THREAD

**Issue by 350d** [rench/homebridge-smarthome#8]
I've successfully added my Mi Gateway to the Homebridge but my Yeelights Bulbs (developer mode on) doesn't work and I have only this error in Homebridge logs:

````
[smarthome-mijia] Initializing smarthome-mijia platform...
[smarthome-broadlink] Initializing smarthome-broadlink platform...
[smarthome-mijia] mijia init upd socket error->ReferenceError: miio is not defined
````
`miio` installed and I can scan for devices tokens.
These bulbs works fine with `homebridge-yeelight` plugin.
My devices part of config.json:

````json
"devices": [
    {
        "sid": "Yeelight 1",
        "name": "Yeelight 1",
        "type": "wifi",
        "model": "light"
    },
    {
        "sid": "Yeelight 2",
        "name": "Yeelight 2",
        "type": "wifi",
        "model": "light"
    }
]
````

**Comment by rench** [comment]
Thanks for your report.
There is missing miio requirement in yeelight.
Just update the new version and try it again.

**Comment by 350d** [comment]
I've updated and restarted and now I have this:
````
homebridge[8938]: Failed to find plugin to handle accessory 620533
homebridge[8938]: Failed to find plugin to handle accessory 61fae4
````
